// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd5cAux2Z8VJElY_Rz56NxumzajOzFCX0',
    appId: '1:1037102373372:web:d5a3589c3a46cac81a3a79',
    messagingSenderId: '1037102373372',
    projectId: 'ligths-ac17d',
    authDomain: 'ligths-ac17d.firebaseapp.com',
    storageBucket: 'ligths-ac17d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-oZ9V7Sdd2nwAXvtQB7i-saKK6_gN5M',
    appId: '1:1037102373372:android:4abbb5cc707ba9771a3a79',
    messagingSenderId: '1037102373372',
    projectId: 'ligths-ac17d',
    storageBucket: 'ligths-ac17d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzfPddRrBtxLNc8kU5P7ORSG3lc70JOw',
    appId: '1:1037102373372:ios:41d8466f135731691a3a79',
    messagingSenderId: '1037102373372',
    projectId: 'ligths-ac17d',
    storageBucket: 'ligths-ac17d.firebasestorage.app',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzfPddRrBtxLNc8kU5P7ORSG3lc70JOw',
    appId: '1:1037102373372:ios:41d8466f135731691a3a79',
    messagingSenderId: '1037102373372',
    projectId: 'ligths-ac17d',
    storageBucket: 'ligths-ac17d.firebasestorage.app',
    iosBundleId: 'com.example.attendence',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd5cAux2Z8VJElY_Rz56NxumzajOzFCX0',
    appId: '1:1037102373372:web:599982dd9e22b3bf1a3a79',
    messagingSenderId: '1037102373372',
    projectId: 'ligths-ac17d',
    authDomain: 'ligths-ac17d.firebaseapp.com',
    storageBucket: 'ligths-ac17d.firebasestorage.app',
  );

}